### ISSUE TITLE
Identify Zindi's definition of challenge difficulty levels

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc#43]
Related to https://github.com/Sage-Bionetworks/rocc/issues/34

Zindi's definition will give us a starting point for setting the difficulty level for a few DREAM challenges.

Filtering by challenge difficulty is one of the three features identified thanks to the user research and that we decided to showcase at S4.

**Comment by jiaxinmachine88** [comment]
I think it may be difficult to get Zindi to share any intel on their Challenge definitions due to the many corporate partners they have. However, I've sent a mail out to ask.

In the meantime, I conducted a quick analysis. I propose for the ROCC team to run with recommendation 2, and focus on building a newcomer category defined by the lack of monetary prize and a more open timeline. 

Here's the link to the analysis: https://docs.google.com/document/d/1mdI4bY4nqfipD39t4vTCBKiEJrSz26gi3MQSNvgGofU/edit
Here's the link to the excel: https://docs.google.com/spreadsheets/d/1frG8tB4x_FbnR1-hMeLHb-4rC7y1Hsbx_7G6vNhZk6k/edit#gid=0
